[manifest]
version = "1.0.0"
priority = 1000



[[patches]] # Now listen IDK why it's 2 slashes but it is..
[patches.regex]
target = '=[SMODS Bakery "src//charm.lua"]'
pattern = "(?<if_c>.*)G.GAME.Bakery_charm == (?<quote>'|\")(?<charm>[a-zA-Z_]*)('|\")(?<after>.*)"
match_indent = true
position = "at"
payload = "$if_c Bakery_API.check_charms($quote$charm$quote)$after"

[[patches]] # Second charm change for startings of parentheses
[patches.regex]
target = '=[SMODS Bakery "src//charm.lua"]'
pattern = "(?<if_c>.*)\\(G.GAME.Bakery_charm == (?<quote>'|\")(?<charm>[a-zA-Z_]*)('|\")(?<after>.*)"
match_indent = true
position = "at"
payload = "$if_c (Bakery_API.check_charms($quote$charm$quote)$after"

[[patches]] # Third charm change for not equal statements (Anaglyph Lens)
[patches.regex]
target = '=[SMODS Bakery "src//charm.lua"]'
pattern = "(?<if_c>.*)G.GAME.Bakery_charm ~= (?<quote>'|\")(?<charm>[a-zA-Z_]*)('|\")(?<after>.*)"
match_indent = true
position = "at"
payload = "$if_c not Bakery_API.check_charms($quote$charm$quote)$after"

# remember to table.remove when removing charms!
# turns out i just nil'd it... oh well
[[patches]]
[patches.pattern]
target = '=[SMODS Bakery "src//charm.lua"]'
pattern = "Bakery_API.guard(function()"
times = 1
position = "after"
match_indent = true
payload = """ -- BEGIN OVERCHARMED CHARM API
Bakery_API.check_charms = function(key)
    -- it's as shrimple as that... i guess!
    if G.GAME.Bakery_charm == nil or G.GAME.Bakery_last_checked_charm == nil then
        G.GAME.Bakery_charm = {}
        G.GAME.Bakery_last_checked_charm = ""
    end
    for k,v in ipairs(G.GAME.Bakery_charm) do
        if v == key then
            G.GAME.Bakery_last_checked_charm = v
            return true
        end 
    end
    return false
end
Bakery_API.find_charm_index = function(key)
    if G.GAME.Bakery_last_checked_charm == "" then return nil end
    if G.GAME.Bakery_charm == nil or G.GAME.Bakery_last_checked_charm == nil then
        G.GAME.Bakery_charm = {}
        G.GAME.Bakery_last_checked_charm = ""
    end

    for k,v in ipairs(G.GAME.Bakery_charm) do
        if v == key then -- key is the charm key
            G.GAME.Bakery_last_checked_charm = v
            return k
        end 
    end
    return nil
end
Bakery_API.find_charm_index_in_area = function(key)
    if G.Bakery_charm_area == nil then return nil end
    for k,v in ipairs(G.Bakery_charm_area.cards) do
        if v.config.center_key == key then
            return k
        end
    end
    return nil
end
-- END OVERCHARMED CHARMAPI
"""

[[patches]] # actually insert it into the table
[patches.pattern]
target = '=[SMODS Bakery "src//charm.lua"]'
pattern = "G.GAME.Bakery_charm = self.config.center_key"
position = "at"
match_indent = true
payload = "table.insert(G.GAME.Bakery_charm,self.config.center_key)"

[[patches]] # remove unequipment
[patches.pattern]
target = '=[SMODS Bakery "src//charm.lua"]'
pattern = """G.P_CENTERS[G.GAME.Bakery_charm]:unequip(G.Bakery_charm_area.cards[1])
            G.GAME.used_jokers[G.GAME.Bakery_charm] = nil
            if not G.Bakery_charm_area.cards[1] then
                sendWarnMessage("No charm was found in G.Bakery_charm_area to destroy.", "Bakery")
            else
                G.Bakery_charm_area.cards[1]:start_dissolve()
            end"""
position = "at"
times = 1
match_indent = true
payload = "-- removed by bakery+" # we dont wanna remove it!

[[patches]]
[patches.regex]
# okay now THIS ONE may be particularly stupid
target = '=[SMODS Bakery "src//charm.lua"]'
pattern = "(?<before>.*)G\\.Bakery_charm_area\\.cards\\[1\\](?<after>.*)"
position = "at"
match_indent = true
payload = "$before G.Bakery_charm_area.cards[Bakery_API.find_charm_index(G.GAME.Bakery_last_checked_charm)]$after"


[[patches]] # Reequip when boss is defeated
[patches.pattern]
target = '=[SMODS Bakery "src//blind.lua"]'
pattern = """G.GAME.Bakery_charm = G.Bakery_charm_area.cards[1].config.center.key
            G.P_CENTERS[G.GAME.Bakery_charm]:equip(G.Bakery_charm_area.cards[1])
            SMODS.recalc_debuff(G.Bakery_charm_area.cards[1])"""
position = "at"
match_indent = true
payload = """for k,v in ipairs(G.GAME.Bakery_charm) do
                local eq_card = G.Bakery_charm_area.cards[Bakery_API.find_charm_index_in_area(v)]
                G.GAME.Bakery_charm[k] = eq_card.config.center_key
                G.P_CENTERS[v]:equip(eq_card)
                SMODS.recalc_debuff(eq_card)
            end"""


[[patches]] # Correct debuffing
[patches.pattern]
target = '=[SMODS Bakery "src//blind.lua"]'
pattern = """G.P_CENTERS[G.GAME.Bakery_charm]:unequip(G.Bakery_charm_area.cards[1])
            G.GAME.Bakery_charm = nil"""
position = "at"
match_indent = true
payload = """for k,v in ipairs(G.GAME.Bakery_charm) do
    local index = Bakery_API.find_charm_index(v)
    local eq_card = G.Bakery_charm_area.cards[Bakery_API.find_charm_index_in_area(v)]
    G.P_CENTERS[v]:unequip(eq_card)
    G.GAME.Bakery_charm[k] = nil -- just to be safe
end"""


[[patches]] # Introversion: Set the joker rate
[patches.pattern]
target = '=[SMODS Bakery "src//charm.lua"]'
pattern = "G.GAME.joker_rate = card.ability.extra.prior"
position = "at"
match_indent = true
payload = "G.GAME.joker_rate = G.GAME.introversion_joker_rate or (card.ability.extra and card.ability.extra.prior)"


[[patches]] # Introversion: Store joker rate
[patches.pattern]
target = '=[SMODS Bakery "src//charm.lua"]'
pattern = """card.ability.extra.prior = G.GAME.joker_rate"""
position = "after"
match_indent = true
payload = """G.GAME.introversion_joker_rate = G.GAME.joker_rate"""

[[patches]] # Cogwheel: Default to 2 antes and 1 card slot if no extra found
[patches.regex]
target = '=[SMODS Bakery "src//charm.lua"]'
pattern = "ease_ante\\((?<neg>-|)card.ability.extra.antes\\)"
position = "at"
times = 2
match_indent = true
payload = """card.ability.antes = (card.ability.extra ~= nil and card.ability.extra.antes) or 2
ease_ante($neg ((card.ability.extra ~= nil and card.ability.extra.antes) or card.ability.antes))"""

[[patches]]
[patches.regex]
target = '=[SMODS Bakery "src//charm.lua"]'
pattern = "change_shop_size\\((?<neg>-|)card.ability.extra.cards\\)"
position = "at"
times = 2
match_indent = true
payload = """card.ability.cards = (card.ability.extra ~= nil and card.ability.extra.cards) or 2
change_shop_size($neg ((card.ability.extra ~= nil and card.ability.extra.cards) or card.ability.cards))"""

 
[[patches]] # patch ante setter
[patches.regex]
target = '=[SMODS Bakery "src//charm.lua"]'
pattern = "G.GAME.round_resets.blind_ante = G.GAME.round_resets.blind_ante (?<val>\\+|-) card.ability.extra.antes"
position = "at"
times = 2
match_indent = true
payload = "G.GAME.round_resets.blind_ante = G.GAME.round_resets.blind_ante $val card.ability.antes"


[[patches]] # PetriDish: Fix setting consumeable card limit by doing or 2 for card.ability.extra
[patches.regex]
target = '=[SMODS Bakery "src//charm.lua"]'
pattern = "G.consumeables.config.card_limit = G.consumeables.config.card_limit (?<val>\\+|-) card.ability.extra"
position = "at"
times = 2
match_indent = true
payload = "G.consumeables.config.card_limit = G.consumeables.config.card_limit $val (card.ability.extra or 2)"


[[patches]] # Charm Object: remove badge that says you can only have 1
[patches.pattern]
target = '=[SMODS Bakery "src//charm.lua"]'
pattern = """info_queue[#info_queue + 1] = {
                    set = "Other",
                    key = "Bakery_charm"
                }"""
position = "at"
match_indent = true
times = 1
payload = ""


[[patches]] # Add more space for charms?
[patches.pattern]
target = '=[SMODS Bakery "src//charm.lua"]'
pattern = "G.Bakery_charm_area = CardArea(0, 0, 0.95 * G.CARD_W, 0.95 * G.CARD_W, {"
position = "at"
times = 1
match_indent = true
payload = "G.Bakery_charm_area = CardArea(2, 0, 2 * G.CARD_W, 0.95 * G.CARD_W, {"

[[patches]]
[patches.pattern]
target = '=[SMODS Bakery "src//charm.lua"]'
pattern = "G.Bakery_charm_area.T.x = G.TILE_W - G.Bakery_charm_area.T.w - 0.5"
position = "at"
times = 1
match_indent = true
payload = "G.Bakery_charm_area.T.x = (G.TILE_W - G.Bakery_charm_area.T.w - 0.5) +1 "

[[patches]]
[patches.pattern]
target = '=[SMODS Bakery "src//charm.lua"]'
pattern = "if G.STAGE == G.STAGES.RUN and G.Bakery_charm_area then"
position = "after"
match_indent = true
payload = """for k,v in ipairs(G.Bakery_charm_area.cards) do
    v.T.y = v.parent.T.y + k*0.5
end"""

[[patches]]
[patches.pattern]
target = '=[SMODS Bakery "test/charm_tests.lua"]'
pattern = """equip 'BakeryCharm_Bakery_Epitaph'
        equip 'BakeryCharm_Bakery_Coin'"""
position = "at"
match_indent = true
payload = """equip 'BakeryCharm_Bakery_Epitaph'
        unequip 'BakeryCharm_Bakery_Epitaph'
        equip 'BakeryCharm_Bakery_Coin'
"""

[[patches]]
[patches.pattern]
target = '=[SMODS Bakery "test/charm_tests.lua"]'
pattern = """Balatest.TestPlay {
    name = 'rune_can_discard_zero',
    category = { 'charms', 'rune' },

    execute = function()
        equip 'BakeryCharm_Bakery_Rune'
    end,
    assert = function()
        local node = { config = {} }
        G.FUNCS.can_discard(node)
        Balatest.assert(node.config.button == 'Bakery_discard_zero')
    end
}
Balatest.TestPlay {
    name = 'rune_cant_discard_zero',
    category = { 'charms', 'rune' },

    discards = 0,
    execute = function()
        equip 'BakeryCharm_Bakery_Rune'
    end,
    assert = function()
        local node = { config = {} }
        G.FUNCS.can_discard(node)
        Balatest.assert(node.config.button ~= 'Bakery_discard_zero')
    end
}
Balatest.TestPlay {
    name = 'rune_discard_zero',
    category = { 'charms', 'rune' },

    hand_size = 8,
    execute = function()
        equip 'BakeryCharm_Bakery_Rune'
        Balatest.q(G.FUNCS.Bakery_discard_zero)
        Balatest.wait_for_input()
    end,
    assert = function()
        Balatest.assert_eq(#G.hand.cards, 10)
    end
}
Balatest.TestPlay {
    name = 'rune_discard_zero_grat',
    category = { 'charms', 'rune' },

    jokers = { 'j_delayed_grat' },
    dollars = 8,
    hand_size = 8,
    execute = function()
        equip 'BakeryCharm_Bakery_Rune'
        Balatest.q(G.FUNCS.Bakery_discard_zero)
        Balatest.end_round()
        Balatest.cash_out()
    end,
    assert = function()
        Balatest.assert_eq(G.GAME.dollars, 0)
    end
}"""
position="at"
match_indent=true
payload = "-- Disabled Rune tests because they were crashing my game for an unknown reason"

[[patches]]
[patches.pattern]
target = '=[SMODS Bakery "test/charm_tests.lua"]'
pattern="local function equip(key)"
position="before"
match_indent=true
payload="""local function unequip(key)
Balatest.q(function()
        G.P_CENTERS[key]:unequip(G.Bakery_charm_area.cards[Bakery_API.find_charm_index_in_area(v)])
    end)
end
"""


[[patches]] # Add unequip button? 👀
[patches.pattern]
target = 'functions/UI_definitions.lua'
pattern = "if card.area == G.shop_vouchers and G.shop_vouchers then --Add a redeem button"
position = 'before'
match_indent = true
times = 1
payload = """
if card.area == G.Bakery_charm_area and G.Bakery_charm_area then -- Selling Card
    base_attach.children.use_button = G.UIDEF.card_focus_button{
        card = card, parent = base_attach, type = 'use',
        func = 'Bakery_can_unequip', button = 'Bakery_unequip_from_shop', card_width = card_width
    }
end"""

[[patches]]
[patches.pattern]
target='=[SMODS Bakery "src//charm.lua"]'
pattern = "function Bakery_API.equip_button(card)"
position="at"
match_indent = true
times = 1
payload = """function G.FUNCS.Bakery_can_unequip(e) -- for now
    if e.config.ref_table.label == "BakeryCharm_Bakery_Ducttape" then
        e.config.colour = G.C.UI.BACKGROUND_INACTIVE
        e.config.button=nil
    else
        e.config.colour = G.C.GREEN
        e.config.button = 'Bakery_unequip'
        e.config.func = "Bakery_can_unequip"
    end
    
end
function G.FUNCS.Bakery_unequip(e)
    local card = e.config.ref_table
    G.P_CENTERS[card.label]:unequip(card)
    if not Bakery_API.find_charm_index(card.label) then -- If we don't find another one
        G.GAME.used_jokers[card.label] = nil
    end
    card:start_dissolve()
end
function Bakery_API.unequip_button(card)
        return {
            n = G.UIT.ROOT,
            config = {
                ref_table = card,
                minw = 1.1,
                maxw = 1.3,
                padding = 0.1,
                align = 'bm',
                colour = G.C.GREEN,
                shadow = true,
                r = 0.08,
                minh = 0.94,
                func = 'Bakery_can_unequip',
                one_press = true,
                button = 'Bakery_unequip',
                hover = true
            },
            nodes = { {
                n = G.UIT.T,
                config = {
                    text = localize('b_Bakery_unequip'),
                    colour = G.C.WHITE,
                    scale = 0.4
                }
            } }
        }
    end
function Bakery_API.equip_button(card)
if card.Bakery_equipped then return Bakery_API.unequip_button(card) end"""

[[patches]] #idk why but i can
[patches.pattern]
target = '=[SMODS Bakery "localization/en-us.lua"]'
pattern = 'b_Bakery_equip = "EQUIP",'
position = "before"
match_indent = true
times = 1
payload = 'b_Bakery_unequip = "UNEQUIP",'

# This is the shop card UI. Why do I need to overwrite that?
# [[patches]]
# [patches.pattern]
# target = 'functions/UI_definitions.lua'
# pattern = """local t2 = card.ability.set == 'BakeryCharm' and Bakery_API.equip_button(card) or card.ability.set == 'Voucher' and {"""
# position = "at"
# match_indent = true
# times = 1
# payload = """local Bakery_function = nil
# print(card.Bakery_equipped)
# if card.Bakery_equipped then print("overcharmed: grabbed unequip button!")
# Bakery_function = Bakery_API.unequip_button(card) else print("overcharmed: grabbed equip button...")
# Bakery_function = Bakery_API.equip_button(card) end
# local t2 = card.ability.set == 'BakeryCharm' and Bakery_function or card.ability.set == 'Voucher' and {"""

[[patches]]
[patches.pattern]
target='=[SMODS Bakery "src//charm.lua"]'
pattern = "return self ~= G.Bakery_charm_area and raw_CardArea_can_highlight(self, card)"
position ="at"
match_indent = true
times = 1
# I hope this wasn't the reason why...
payload = "return raw_CardArea_can_highlight(self, card)"

[[patches]] # DuctTape: Remove the if statement checking for it when you buy
[patches.pattern]
target = '=[SMODS Bakery "src//charm.lua"]'
pattern = "if G.GAME.Bakery_charm == 'BakeryCharm_Bakery_DuctTape' or"
position = "at"
match_indent = true
times = 1
payload = "if"

[[patches]] 
[patches.pattern]
target = '=[SMODS Bakery "src//charm.lua"]'
pattern = "if G.GAME.Bakery_charm then"
times = 1
position = "before"
match_indent = true
payload = """self.Bakery_equipped = true"""

# [[patches]] # Equip button: Remove equip button if alr equipped
# [patches.pattern]
# target="card.lua"
# pattern = "function Card:highlight(is_higlighted)"
# position = "after"
# match_indent = true
# payload = """if self.Bakery_equipped then self.children.buy_button.states.visible = false return end"""

[[patches]]
[patches.pattern]
target = '=[SMODS Bakery "src//charm.lua"]'
pattern = """e.config.colour = G.C.UI.BACKGROUND_INACTIVE
e.config.button = nil"""
times = 1
position = "after"
match_indent = true
payload = """
elseif next(SMODS.deepfind(e.children,'Bakery_equipped','i',true)) or false then
e.config.colour = G.C.GREEN
e.config.button = 'Bakery_unequip'
e.config.func = "Bakery_can_unequip"
"""

[[patches]]
[patches.pattern]
target = '=[SMODS Bakery "src//charm.lua"]'
pattern = "type = 'joker',"
times = 1 
match_indent = true
position = "at"
payload = "type = 'charm',"

[[patches]]
[patches.pattern]
target="functions/UI_definitions.lua"
pattern = "if card.ability.consumeable then"
position = "at"
match_indent = true
payload = "if card.ability.consumeable and not card.area.config.type == 'charm' then"

[[patches]]
[patches.pattern]
target="functions/UI_definitions.lua"
pattern = "if card.area and card.area.config.type == 'joker' then"
position = "before"
match_indent = true
payload = """
if card.label:sub(1,11) == "BakeryCharm" then
    return Bakery_API.unequip_button(card)
end
"""